### ISSUE TITLE
Ignored a message from User

### ISSUE THREAD

**Issue by DonHansDampf** [pyed/rtelegram#1]
I get the error about the `Ignored a message from` meanwhile the user is correct.
```

2017/07/11 16:43:16 [INFO] Token=xxxxxxxxxxxxxxxxx
		Masters=[@User]
		URL=localhost:443
2017/07/11 16:43:16 [INFO] Authorized: Bot
2017/07/11 16:43:18 [INFO] Ignored a message from: User
```

**Comment by pyed** [comment]
I doubt that you have the correct user, double check that.

**Comment by DonHansDampf** [comment]
I already did. It is exactly the same. I also copied the User from the Error Message and used it as master. The User is something like ‘JupiterEuropaIo’. So no numbers or symbols.

**Comment by pyed** [comment]
it was "mistakingly" case-sensitive, [v1.1](https://github.com/pyed/rtelegram/releases/tag/v1.1) should fix that.
