### ISSUE TITLE
[Request] Add torrrent with label

### ISSUE THREAD

**Issue by tulkarxxx** [pyed/rtelegram#8]
Hi, it will be nice if we were able to add torrent with specific labels to classiffy downloads for external software

Thanks

**Comment by pyed** [comment]
if you referring to ruTorrent labels, then you can already do that by writing a comment on your file when you send it to your telegram bot, [read here](https://github.com/pyed/rtelegram/blob/bd0afc46b065cb8a797a2661cdee787cc7091cd8/recieveTorrent.go#L72-L75) for how to pass options such as labels or download location 

Just make sure to install rtelegram via `go get ...etc`

**Comment by tulkarxxx** [comment]
working like a charm!! Thanks
